# Generated by Django 5.1.5 on 2026-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
