# Generated by Django 5.1.5 on 2026-08-17 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('avatar', 'Profil rasmi'), ('resource', 'Kurs resursi'), ('lesson_video', 'Dars videosi'), ('submission', 'Topshiriq fayli')], default='resource', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('storage_key', models.CharField(max_length=300, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Yuklanmoqda'), ('ready', 'Tayyor')], default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayllar',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('zip', 'ZIP'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Rasm'), ('presentation', 'Taqdimot'), ('spreadsheet', 'Jadval'), ('document', 'Hujjat'), ('code', 'Kod'), ('url', 'Tashqi havola')], default='document', max_length=16)),
                ('folder', models.CharField(choices=[('lessons', 'Dars resurslari'), ('assignments', 'Topshiriq resurslari'), ('quizzes', 'Test resurslari'), ('general', 'Umumiy kurs resurslari')], default='general', max_length=20)),
                ('category', models.CharField(blank=True, default='umumiy', max_length=60)),
                ('size_kb', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, default='')),
                ('favorite', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('archived', 'Arxiv')], default='active', max_length=16)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resurs',
                'verbose_name_plural': 'Resurslar',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'purpose', 'status'], name='resources_f_owner_i_008907_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course', 'status'], name='resources_r_course__6bc438_idx'),
        ),
    ]
